#!/bin/bash
yakuake
pkill trayer; trayer --edge top --SetDockType true --align right --height 14 \
      --widthtype request --tint 0x000000 --transparent true --alpha 0 &

pkill nm-applet; nm-applet &
exec xmonad
