---
- name: Check if xmobar is already installed
  shell: command -v xmobar
  ignore_errors: yes
  register: xmobar_check

- name: Install xmobar
  package:
    name: xmobar
    state: present
  become: yes
  when: xmobar_check.stdout == ""

- name: Copy xmobar config
  synchronize:
    dest: "{{ ansible_user_dir }}"
    src: "../../../.xmobarrc"
    owner: yes

- name: Copy bottom xmobar config
  synchronize:
    dest: "{{ ansible_user_dir }}"
    src: "../../../.xmobarrc-bottom"
    owner: yes
