---
- name: Install zsh
  package:
    name: zsh
    state: present
  become: yes

- name: Install oh-my-zsh
  command: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  owner: yes

- name: Setup oh-my-zsh gruvbox theme
  command: curl -L https://raw.githubusercontent.com/sbugzu/gruvbox-zsh/master/gruvbox.zsh-theme > ~/.oh-my-zsh/custom/themes/gruvbox.zsh-theme
  owner: yes

- name: Setup oh-my-zsh zsh-autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Setup oh-my-zsh zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Setup oh-my-zsh zsh-z plugin
  git:
    repo: https://github.com/agkozak/zsh-z
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-z"

- name: Copy .zshrc
  synchronize:
    dest: "{{ ansible_user_dir }}"
    src: "../../../.zshrc"

- name: Copy .zshrc_local
  synchronize:
    dest: "{{ ansible_user_dir }}"
    src: "../../../.zshrc_local"
