---
- name: Check if clipmenu is already installed
  shell: command -v clipmenu
  ignore_errors: yes
  register: clipmenu_check

- name: Install clipmenu
  package:
    name: clipmenu
    state: present
  when: clipmenu_check.stdout == ""
