---
- name: Check if xmonad is already installed
  shell: command -v xmonad
  ignore_errors: yes
  register: xmonad_check

- name: Install xmonad
  package:
    name:
      - xmonad
      - xmonad-contrib
    state: present
  become: yes
  when: xmonad_check.stdout == ""

- name: Configure xmonad
  synchronize:
    dest: "{{ ansible_user_dir }}"
    src: "../../../.xmonad"
    owner: yes

- name: Copy script required by xmonad
  synchronize:
    dest: "{{ ansible_user_dir }}"
    src: "../../../scripts"
    owner: yes
