---
- name: Check if nvim is already installed
  shell: command -v nvim
  ignore_errors: yes
  register: nvim_check

- name: Install neovim
  package:
    name: neovim
    state: present
  become: yes
  when: nvim_check.stdout == ""

- name: Copy .vimrc
  synchronize:
    dest: "{{ ansible_user_dir }}"
    src: "../../../.vimrc"
    owner: yes

- name: Copy .vim folder
  synchronize:
    dest: "{{ ansible_user_dir }}"
    src: "../../../.vim"
    owner: yes

- name: Copy nvim folder
  synchronize:
    dest: "{{ ansible_user_dir }}/.config/"
    src: "../../../.config/nvim"
    owner: yes

- name: Install pynvim
  pip:
    name: pynvim

- name: Install neovim gem
  community.general.gem:
    name: neovim
    norc: false

- name: Install npm neovim
  community.general.npm:
    name: neovim
    global: yes
  become: yes

- name: Install diagnostic languageserver
  community.general.npm:
    name: diagnostic-languageserver
    global: yes
  become: yes

- name: Install instant markdown daemon
  community.general.npm:
    name: instant-markdown-d
    global: yes
  become: yes

- name: Install typescript
  community.general.npm:
    name: typescript
    global: yes
  become: yes

- name: Install typescript language server
  community.general.npm:
    name: typescript-language-server
    global: yes
  become: yes

- name: Configure neovim plugins
  command: nvim --headless +PlugInstall +qa
