---
- name: Install awesome fonts
  package:
    name:
      - otf-font-awesome
      - ttf-font-awesome
    state: present
  become: yes

- name: Install custom hacked font
  synchronize:
    dest: "{{ ansible_user_dir }}/.local/share/"
    src: "../../../.local/share/fonts"

- name: Configure powerline fonts
  synchronize:
    dest: "{{ ansible_user_dir }}/.config/"
    src: "../../../.config/fontconfig"

- name: Install nerd fonts complete
  kewlfft.aur.aur:
    use: yay
    name:
      - nerd-fonts-git
    state: present

- name: Update the fontconfig cache
  command: fc-cache
