---
- name: Install otf awesome fonts
  package:
    name: otf-font-awesome
    state: present
  become: yes

- name: Install ttf awesome fonts
  package:
    name: ttf-font-awesome
    state: present
  become: yes

- name: Install custom hacked font
  synchronize:
    dest: "{{ ansible_user_dir }}/.local/share/fonts"
    src: "../../../.local/share/fonts"

- name: Install nerd fonts complete
  kewlfft.aur.aur:
    use: yay
    name:
      - nerd-fonts-complete
    state: present

- name: Update the fontconfig cache
  command: fc-cache
