---
- name: Install awesome fonts
  package:
    name:
      - otf-font-awesome
      - ttf-font-awesome
    state: present
  become: yes

- name: Install custom hacked font
  synchronize:
    dest: "{{ ansible_user_dir }}/.local/share/"
    src: "../../../.local/share/fonts"

- name: Install nerd fonts complete
  kewlfft.aur.aur:
    use: yay
    name:
      - nerd-fonts-complete
    state: present
  register: nerd_fonts_output

- debug:
    var: nerd_fonts_output.stdout_lines

- name: Update the fontconfig cache
  command: fc-cache
